############# baseline parameters #############

SAC:
    lr: 0.001
    tau: 0.005
    update_iteration: 3
    gamma: 0.99
    alpha: 0.2
    max_buffer_size: 4000
    pretrain_buffer_size: 50
    hidden_dim: 64
    batch_size: 256
    model_path: './model'
    model_id: 1
    min_Val: 1.0e-7

